version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: QhapaqTour
    ports:
      - '5432:5432'